### ISSUE TITLE
Optimize File Manipulation Logic in `fileManipulate.ts`

### ISSUE THREAD

**Issue by Mefisto04** [yamadashy/repopack#112]
The current implementation of the file manipulation logic in `repopack/src/core/file/fileManipulate.ts` can be optimized for performance. Several areas, such as regex handling, string trimming, and quote matching, can be made more efficient.

**Proposed Optimizations**:

1. **Improve Docstring Removal Regex**:  
   Simplify and optimize the regex used for removing docstrings in `PythonManipulator`.

2. **Optimize Quote Matching in `removeHashComments`**:  
   Enhance the logic to reduce redundant `slice` operations and improve performance in detecting quoted strings.

3. **Refactor `searchInPairs` Binary Search**:  
   Streamline the binary search function for checking if a hash is inside a string literal.

4. **Enhance `rtrimLines` Function**:  
   Use a more efficient method to trim trailing spaces and tabs from lines.

5. **Lazy Instantiate Manipulators**:  
   Instantiate manipulators in the `manipulators` object only when needed to improve memory usage.

---

**Expected Benefits**:  
- Faster file manipulation for large files.
- Better memory efficiency.
- Cleaner, more maintainable code.

I'd like to contribute to optimizing the file manipulation logic in `fileManipulate.ts` as described in the issue. Could you please assign it to me so I can start working on it?

Thanks!

**Comment by Mefisto04** [comment]
hey @yamadashy, please go though this issue on your leisure

**Comment by yamadashy** [comment]
Thank you for your detailed suggestions, @Mefisto04! 

Regarding the PythonManipulator, we actually addressed this recently in [PR #81](https://github.com/yamadashy/repopack/pull/81). The current implementation is complex because simple regex matching proved insufficient for handling all edge cases in Python docstrings. However, if you can find a way to achieve the same functionality using regex, that would be a great improvement!

For the other suggestions:

1. Optimizing quote matching in `removeHashComments`
2. Refactoring `searchInPairs` binary search
3. Enhancing the `rtrimLines` function
4. Lazy instantiation of manipulators

These all sound like excellent ideas that could significantly improve performance. I'd be grateful if you could work on these optimizations.
I look forward to seeing your contributions!

**Comment by Mefisto04** [comment]
sure, please assign this so that i will start working on it, or else i will directly send the PR of it.

**Comment by Mefisto04** [comment]
@yamadashy #121

**Comment by Mefisto04** [comment]
@yamadashy , implemented the regex simplification, PR #122

**Comment by yamadashy** [comment]
@Mefisto04
Thank you so much for not only proposing these excellent optimizations but also implementing them yourself!

I'm thrilled to announce that your improvements have been merged and released in version 0.1.42. 
https://github.com/yamadashy/repopack/releases/tag/v0.1.42

Thank you again for your outstanding contribution!

**Comment by Mefisto04** [comment]
@yamadashy 
Thank you for the opportunity to contribute! It was a pleasure working on the optimizations, and I'm glad they could be of value. I look forward to collaborating more and making further contributions together!

**Comment by yamadashy** [comment]
Looking forward to future collaborations.I'll go ahead and close this issue now. Great work!
